ln -sfn $PWD/zshrc $HOME/.zshrc
ln -sfn $PWD/tmux.conf $HOME/.tmux.conf
ln -sfn $PWD/vimrc $HOME/.vimrc
ln -sfn $PWD/alacritty.yml $HOME/.alacritty.yml
ln -sfn $PWD/gitconfig $HOME/.gitconfig
ln -sfn $PWD/gitignore_global $HOME/.gitignore_global
ln -sfn $PWD/karabiner.json $HOME/.config/karabiner/karabiner.json
ln -sfn $PWD/com.googlecode.iterm2.plist $HOME/Library/Preferences/com.googlecode.iterm2.plist
ln -sfn $PWD/teamocil $HOME/.teamocil
ln -sfn $PWD $HOME/.dotfiles
ln -sfn $PWD/init.vim $HOME/.config/nvim/init.vim
